#:import App kivymd.app.MDApp
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_main.kv
#:include screen_registration.kv
#:include screen_log.kv
#:include screen_AddTrash.kv

WindowManager:
    LoginWindow:
    MainWindow:
    RegistrationWindow:
    AddTrashWindow:

#Nastavení

<ScreenManager>:
    transition: NoTransition()

#Tamplaty
<Navbar@BoxLayout>:

#Screeny

<LoginWindow>:
<MainWindow>:
<RegistrationWindow>:
<AddTrashWindow>:







